# Generated by Django 2.0.2 on 2018-02-23 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_news_feature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='feature',
            field=models.FileField(default=None, upload_to='./upload/'),
        ),
    ]
