# Generated by Django 2.0.2 on 2018-02-27 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20180223_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='experts',
            field=models.TextField(default='', verbose_name='摘要'),
        ),
    ]
