# Generated by Django 2.0.2 on 2018-02-22 13:12

from django.db import migrations, models
import froala_editor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50, verbose_name='标签')),
                ('name', models.CharField(max_length=50, verbose_name='学校名')),
                ('introduce', froala_editor.fields.FroalaField()),
            ],
        ),
    ]
