# Generated by Django 2.0.2 on 2018-02-22 08:21

from django.db import migrations, models
import froala_editor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50, verbose_name='标签')),
                ('name', models.CharField(max_length=50, verbose_name='医院名')),
                ('introduce', froala_editor.fields.FroalaField()),
            ],
        ),
    ]
