# Generated by Django 2.0.2 on 2018-02-23 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hospital',
            options={'verbose_name': '医院', 'verbose_name_plural': '医院'},
        ),
        migrations.AddField(
            model_name='hospital',
            name='order',
            field=models.IntegerField(default=0, verbose_name='顺序'),
        ),
    ]
